### ISSUE TITLE
[Bug]: `ENARX_BACKEND=sgx cargo test` fails

### ISSUE THREAD

**Issue by jarkkojs** [enarx/enarx#1331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Current Behaviour

```
$ ENARX_BACKEND=sgx cargo test
    Finished test [unoptimized + debuginfo] target(s) in 0.06s
     Running unittests (target/debug/deps/enarx-4894057a6dbd3cd9)

running 4 tests
test backend::sev::snp::certs::test::test_vcek_url ... ok
test backend::sev::snp::tests::test_const_id_macro ... ok
test cli::sev::tests::test_merge_vcek_stack ... ok
test workldr::wasmldr::test::is_builtin ... ok

test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/integration_tests.rs (target/debug/deps/integration_tests-313fc0036677118f)

running 27 tests
Error: Input/output error (os error 5)
Error: Input/output error (os error 5)
Error: Input/output error (os error 5)
test bind ... Error: Input/output error (os error 5)
FAILED
test clock_gettime ... FAILED
test exit_one ... ok
test close ... FAILED
Error: Input/output error (os error 5)
test geteuid ... FAILED
Error: Input/output error (os error 5)
test get_att ... FAILED
Error: Input/output error (os error 5)
test getgid ... FAILED
Error: Input/output error (os error 5)
test getuid ... FAILED
Error: Input/output error (os error 5)
test listen ... FAILED
Error: Input/output error (os error 5)
test getegid ... FAILED
Error: Input/output error (os error 5)
test exit_zero ... FAILED
Error: Input/output error (os error 5)
test read_udp ... FAILED
Error: Input/output error (os error 5)
test read ... FAILED
Error: Input/output error (os error 5)
test readv ... FAILED
Error: Input/output error (os error 5)
test sgx_get_att_quote ... FAILED
Error: Input/output error (os error 5)
test sgx_get_att_quote_size ... FAILED
Error: Input/output error (os error 5)
test socket ... FAILED
Error: Input/output error (os error 5)
test uname ... FAILED
test unix_echo ... ignored
test write_emsgsize ... ignored
test write_stderr ... ignored
Error: Input/output error (os error 5)
test write_stdout ... FAILED
Error: Input/output error (os error 5)
test cpuid ... FAILED
Error: Input/output error (os error 5)
test memory_stress_test ... FAILED
Error: Input/output error (os error 5)
test memspike ... FAILED
Error: Input/output error (os error 5)
test echo ... FAILED
Error: Input/output error (os error 5)
test rust_sev_attestation ... FAILED

failures:

---- bind stdout ----
thread 'bind' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/common/mod.rs:179:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- clock_gettime stdout ----
thread 'clock_gettime' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/common/mod.rs:179:5

---- close stdout ----
thread 'close' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/common/mod.rs:179:5

---- geteuid stdout ----
thread 'geteuid' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/common/mod.rs:179:5

---- get_att stdout ----
thread 'get_att' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/common/mod.rs:179:5

---- getgid stdout ----
thread 'getgid' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/common/mod.rs:179:5

---- getuid stdout ----
thread 'getuid' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/common/mod.rs:179:5

---- listen stdout ----
thread 'listen' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/common/mod.rs:179:5

---- getegid stdout ----
thread 'getegid' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/common/mod.rs:179:5

---- exit_zero stdout ----
thread 'exit_zero' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/common/mod.rs:179:5

---- read_udp stdout ----
thread 'read_udp' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `65507`: Expected length of stdout output differs', tests/common/mod.rs:25:5

---- read stdout ----
thread 'read' panicked at 'assertion failed: `(left == right)`
  left: `[]`,
 right: `[104, 101, 108, 108, 111, 32, 119, 111, 114, 108, 100, 10]`: Expected contents of stdout output differs', tests/common/mod.rs:158:13

---- readv stdout ----
thread 'readv' panicked at 'assertion failed: `(left == right)`
  left: `[]`,
 right: `[104, 101, 108, 108, 111, 44, 32, 119, 111, 114, 108, 100, 104, 101, 108, 108, 111, 44, 32, 119, 111, 114, 108, 100, 104, 101, 108, 108, 111, 44, 32, 119, 111, 114, 108, 100]`: Expected contents of stdout output differs', tests/common/mod.rs:158:13

---- sgx_get_att_quote stdout ----
thread 'sgx_get_att_quote' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/common/mod.rs:179:5

---- sgx_get_att_quote_size stdout ----
thread 'sgx_get_att_quote_size' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/common/mod.rs:179:5

---- socket stdout ----
thread 'socket' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/common/mod.rs:179:5

---- uname stdout ----
thread 'uname' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/common/mod.rs:179:5

---- write_stdout stdout ----
thread 'write_stdout' panicked at 'assertion failed: `(left == right)`
  left: `[]`,
 right: `[104, 105, 10]`: Expected contents of stdout output differs', tests/common/mod.rs:158:13

---- cpuid stdout ----
thread 'cpuid' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/common/mod.rs:179:5

---- memory_stress_test stdout ----
thread 'memory_stress_test' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/common/mod.rs:179:5

---- memspike stdout ----
thread 'memspike' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/common/mod.rs:179:5

---- echo stdout ----
thread '<unnamed>' panicked at 'failed to write stdin to child: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', tests/common/mod.rs:110:18
thread 'echo' panicked at 'failed to provide input for process `echo`', tests/common/mod.rs:127:13

---- rust_sev_attestation stdout ----
thread 'rust_sev_attestation' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: Expected exit status differs.', tests/common/mod.rs:179:5


failures:
    bind
    clock_gettime
    close
    cpuid
    echo
    exit_zero
    get_att
    getegid
    geteuid
    getgid
    getuid
    listen
    memory_stress_test
    memspike
    read
    read_udp
    readv
    rust_sev_attestation
    sgx_get_att_quote
    sgx_get_att_quote_size
    socket
    uname
    write_stdout

test result: FAILED. 1 passed; 23 failed; 3 ignored; 0 measured; 0 filtered out; finished in 0.18s

error: test failed, to rerun pass '--test integration_tests'
```

### Expected Behaviour

Tests succeed.

### Environment Information

```
❯ git bisect log
git bisect start
# good: [0a1c71e56687a289125ab6bbc98a54dbea280ce0] Use alternatives to deprecated types in process_control.
git bisect good 0a1c71e56687a289125ab6bbc98a54dbea280ce0
# bad: [68e136d1aa1749166b453e3575cd8b657534728f] shim-sgx: Implement get_attestation()
git bisect bad 68e136d1aa1749166b453e3575cd8b657534728f
# bad: [91d79e35b29f68ddffa60a305421fdc355ac424c] build(deps): bump compiler_builtins in /internal/shim-sev
git bisect bad 91d79e35b29f68ddffa60a305421fdc355ac424c
# bad: [48f1b21c5edcf3451cc84d223f9d7164b7ab01b8] build(deps): bump libc from 0.2.114 to 0.2.116 in /internal/shim-sgx
git bisect bad 48f1b21c5edcf3451cc84d223f9d7164b7ab01b8
# good: [ac87c6b306046c20cba7eac9c925b595786f17b4] build(deps): bump protobuf-codegen-pure from 2.25.2 to 2.26.1
git bisect good ac87c6b306046c20cba7eac9c925b595786f17b4
# bad: [76696e99866ef85c15a78871b43a2626ac63c52b] build(deps): bump libc from 0.2.114 to 0.2.116
git bisect bad 76696e99866ef85c15a78871b43a2626ac63c52b
# bad: [55caa95159c9fcecc5f7ae62cf900f3b328cf148] feat(shim-sgx): enable AVX2 and AVX512 usage in the enclave
git bisect bad 55caa95159c9fcecc5f7ae62cf900f3b328cf148
# first bad commit: [55caa95159c9fcecc5f7ae62cf900f3b328cf148] feat(shim-sgx): enable AVX2 and AVX512 usage in the enclave
```

**Comment by npmccallum** [comment]
@haraldh Looks like your PR may have broken things. Perhaps only on older hardware?

**Comment by npmccallum** [comment]
@jarkkojs Please revert that patch locally and keep pressing forward.

**Comment by jarkkojs** [comment]
Just making a note that this form is a bit too "wired" to very limited subset of system bugs. E.g. `git bisect` is not meant for any of the existing sections. "Steps to reproduce" is also a conflicting section with the first section, which makes the form somewhat confusing.

Probably 90% times people will provide all that to current and expected behavior. For that remaining 10% you ask the missing details. It's not huge problem really. We are essentially now asking 2x current behavior and 1x expected behavior.

I'm happy make an issue. @platten ?

**Comment by jarkkojs** [comment]
> @jarkkojs Please revert that patch locally and keep pressing forward.

Sure just a few more hours of sleep :-) Had my alarm waking up too early.

**Comment by haraldh** [comment]
Even on my small home SGX server:

```
$ ENARX_BACKEND=sgx cargo test
[…]
     Running unittests (target/debug/deps/enarx-9461f041f316df2a)
[…]
test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/c_integration_tests.rs (target/debug/deps/c_integration_tests-34ffd234bf6e5871)
[…]
test result: ok. 19 passed; 0 failed; 2 ignored; 0 measured; 0 filtered out; finished in 24.04s

     Running tests/rust_integration_tests.rs (target/debug/deps/rust_integration_tests-fbbb0e3e78f09726)
[…]
test result: ok. 5 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out; finished in 8.60s

     Running tests/wasmldr_tests.rs (target/debug/deps/wasmldr_tests-a536b1b03e1c813b)
[…]
test result: ok. 9 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 37.42s
```
$ ENARX_BACKEND=sgx cargo run -- info
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/enarx info`
Backend: sgx
 ✔ System Info: Linux sgx.fritz.box 5.15.12-200.fc35.x86_64 #1 SMP Wed Dec 29 15:03:38 UTC 2021 x86_64 (none)
 ✔ Driver: /dev/sgx_enclave
 ✔ CPU: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | GenuineIntel
 ✔  SGX Support
 ✔   Version 1
 ✔   Version 2
 ✔   FLC Support
 ✔   Max Size (32-bit): 2 GiB
 ✔   Max Size (64-bit): 128 TiB
 ✔   MiscSelect: EXINFO
 ✔   Features: DEBUG | MODE64BIT | PROVISIONING_KEY | EINIT_KEY | KSS
 ✔   Xfrm: X87 | SSE | AVX | YMM | OPMASK | ZMM_HI256 | HI16_ZMM | MPK
 ✔   EPC Size: 188 MiB
```

```
$ cpuid -1| grep AVX
      AVX: advanced vector extensions         = true
      AVX2: advanced vector extensions 2       = true
      AVX512F: AVX-512 foundation instructions = true
      AVX512DQ: double & quadword instructions = true
      AVX512IFMA: fused multiply add           = true
      AVX512PF: prefetch instructions          = false
      AVX512ER: exponent & reciprocal instrs   = false
      AVX512CD: conflict detection instrs      = true
      AVX512BW: byte & word instructions       = true
      AVX512VL: vector length                  = true
      AVX512VBMI: vector byte manipulation     = true
      AVX512_VBMI2: byte VPCOMPRESS, VPEXPAND  = true
      AVX512_VNNI: neural network instructions = true
      AVX512_BITALG: bit count/shiffle         = true
      AVX512: VPOPCNTDQ instruction            = true
      AVX512_4VNNIW: neural network instrs     = false
      AVX512_4FMAPS: multiply acc single prec  = false
      AVX512_VP2INTERSECT: intersect mask regs = false
         XCR0 supported: AVX state            = true
         XCR0 supported: AVX-512 opmask       = true
         XCR0 supported: AVX-512 ZMM_Hi256    = true
         XCR0 supported: AVX-512 Hi16_ZMM     = true
   AVX/YMM features (0xd/2):
      AVX/YMM save state byte size             = 0x00000100 (256)
      AVX/YMM save state byte offset           = 0x00000240 (576)
   AVX-512 opmask features (0xd/5):
      AVX-512 opmask save state byte size      = 0x00000040 (64)
      AVX-512 opmask save state byte offset    = 0x00000440 (1088)
   AVX-512 ZMM_Hi256 features (0xd/6):
      AVX-512 ZMM_Hi256 save state byte size   = 0x00000200 (512)
      AVX-512 ZMM_Hi256 save state byte offset = 0x00000480 (1152)
   AVX-512 Hi16_ZMM features (0xd/7):
      AVX-512 Hi16_ZMM save state byte size    = 0x00000400 (1024)
      AVX-512 Hi16_ZMM save state byte offset  = 0x00000680 (1664)
```

@jarkkojs what is your system?

**Comment by haraldh** [comment]
Especially this one:
```
 ✔   Xfrm: X87 | SSE | AVX | YMM | OPMASK | ZMM_HI256 | HI16_ZMM | MPK
 ```

**Comment by jarkkojs** [comment]
```
processor	: 5
vendor_id	: GenuineIntel
cpu family	: 6
model		: 158
model name	: Intel(R) Core(TM) i5-9600KF CPU @ 3.70GHz
stepping	: 12
microcode	: 0xea
cpu MHz		: 3699.999
cache size	: 9216 KB
physical id	: 0
siblings	: 6
core id		: 5
cpu cores	: 6
apicid		: 10
initial apicid	: 10
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust sgx bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp sgx_lc md_clear flush_l1d arch_capabilities
vmx flags	: vnmi preemption_timer invvpid ept_x_only ept_ad ept_1gb flexpriority tsc_offset vtpr mtf vapic ept vpid unrestricted_guest ple shadow_vmcs pml ept_mode_based_exec
bugs		: spectre_v1 spectre_v2 spec_store_bypass mds swapgs taa itlb_multihit srbds
bogomips	: 7399.70
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:
```

**Comment by jarkkojs** [comment]
```
❯ ENARX_BACKEND=sgx cargo run -- info
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/enarx info`
Backend: sgx
 ✔ Driver: /dev/sgx_enclave
 ✔ CPU: Intel(R) Core(TM) i5-9600KF CPU @ 3.70GHz | GenuineIntel
 ✔  SGX Support
 ✔   Version 1
 ✗   Version 2
 ✔   FLC Support
 ✔   Max Size (32-bit): 2 GiB
 ✔   Max Size (64-bit): 64 GiB
 ✔   MiscSelect: (empty)
 ✔   Features: DEBUG | MODE64BIT | PROVISIONING_KEY | EINIT_KEY
 ✔   Xfrm: X87 | SSE | AVX | YMM | BNDREG | BNDCSR
 ✔   EPC Size: 94 MiB
Backend: sev
 ✗ Driver: /dev/sev
 ✗  SEV is enabled in host kernel
 ✗  /dev/sev is readable by user
 ✗  /dev/sev is writable by user
 ✔ Driver: /dev/kvm
 ✔  API Version: 12
 ✔ MEMLOCK rlimit allows for: ~3518437208883 keeps (soft limit = 18446744073709551615 bytes, hard limit = 18446744073709551615 bytes)
 ✗ CPU: Intel(R) Core(TM) i5-9600KF CPU @ 3.70GHz | GenuineIntel
 ✗  Microcode support
 ✗  Secure Memory Encryption (SME)
 ✗   Physical address bit reduction
 ✗   C-bit location in page table entry
 ✗  Secure Encrypted Virtualization (SEV)
 ✗   Number of encrypted guests supported simultaneously
 ✗   Minimum ASID value for SEV-enabled, SEV-ES disabled guest
 ✗  Secure Encrypted Virtualization Encrypted State (SEV-ES)
 ✗  Page Flush MSR available
Backend: kvm
 ✔ Driver: /dev/kvm
 ✔  API Version: 12
 ✔ CPU: Intel(R) Core(TM) i5-9600KF CPU @ 3.70GHz | GenuineIntel
```

**Comment by haraldh** [comment]
Ah, ok...
```
 ✔   Xfrm: X87 | SSE | AVX | YMM | BNDREG | BNDCSR
```

@npmccallum you make a decision what's the minimum we support.

**Comment by jarkkojs** [comment]
I see corner case hardware similar as having unit tests testing corner cases, assuming that it does not prevent e.g. `AVX512` being able to run same workload with bunch of both optimal and sub-optimal hardware gives certainty that software does not fall apart.

**Comment by npmccallum** [comment]
@jarkkojs @haraldh Our target platform is Ice Lake.

**Comment by jarkkojs** [comment]
So I think we can close this as my XPS13 laptop has meets the requirements. Do we have documented somewhere the minimum hardware requirements. Just saying that Enarx requires at minimum SGX2 capable hardware is enough. @haraldh

**Comment by jarkkojs** [comment]
Also does Enarx have an explicit check for SGX2, i.e. it should even try to do anything on non-SGX2 hardware?

**Comment by haraldh** [comment]
We are not using any SGX2 specific stuff right now, so it would work with SGX1 and FLC currently.... Besides AVX512, which hit you.

**Comment by jarkkojs** [comment]
IMHO, it's good to eventually replace SGX1 code with only SGX2 based solutions and carry an obsolete legacy.

**Comment by jarkkojs** [comment]
I.e. there's only one user userbase I'm aware of SGX1+FLC, which is me.

**Comment by npmccallum** [comment]
Yes. Correct. Closing.
