### ISSUE TITLE
[Infrastructure]: Post-process log with syscall name substitution

### ISSUE THREAD

**Issue by jarkkojs** [enarx/enarx#1625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Description

```
cat /proc/kallsyms | \
           sed -n '/call_meta__/p' | \
           sed 's/.*call_meta__\(.*\)/\1/g; s/\(.*\)/s\/syscall SYS_\1\/syscall \1\//; 1i #include <sys/syscall.h>' | \
           gcc -E -P - | \
           grep -v 'SYS_' | \
           sort -n | \
           uniq | \
           xargs -I{} sed -i '{}' 8_Run\ actions-rscargo@v1.txt
```

**Comment by jarkkojs** [comment]
E.g.

```
2022-04-02T06:29:48.2149957Z syscall write = 16
2022-04-02T06:29:48.2150769Z syscall exit [src/backend/sgx/thread.rs:265] &syscall = Payload {
```

Improves the developer experience a lot.

**Comment by jarkkojs** [comment]
@haraldh, @npmccallum: What do you think?

**Comment by jarkkojs** [comment]
After this I also do:

```bash
sed -i '/syscall clock_gettime/,+16 d' 8_Run\ actions-rscargo@v1-filter-clock_gettime.txt
```

Results:

```
Downloads/tmp/enarx sev nightly debug with dbg on  main 
$ wc -l 8_Run\ actions-rscargo@v1.txt
1406935 8_Run actions-rscargo@v1.txt

Downloads/tmp/enarx sev nightly debug with dbg on  main 
$ wc -l 8_Run\ actions-rscargo@v1-filter-clock_gettime.txt
12646 8_Run actions-rscargo@v1-filter-clock_gettime.txt
```

**Comment by jarkkojs** [comment]
Maybe CI could produce a supplemental log with this post-processing? It does not take long, as long as long as `sys_clock_gettime` is filtered out.

**Comment by jarkkojs** [comment]
After:
```
    Finished test [unoptimized + debuginfo] target(s) in 0.23s
     Running tests/wasmldr_tests.rs (target/debug/deps/wasmldr_tests-e49c216cecd40c1f)

running 1 test
syscall mmap M 0x007f2ffffff000 0x00000000000548
= 0x7f2ffffff000
syscall arch_prctl = 0
syscall set_tid_address = 1
syscall poll [src/backend/sgx/thread.rs:298] &_syscall = Payload {
    num: 7,
    argv: [
        0,
        3,
        0,
        0xffffffffffffffff,
        0xffffffffffffffff,
        0xffffffffffffffff,
    ],
    ret: [
        0xffffffffffffffda,
        0,
    ],
}
= 1
syscall rt_sigaction = 0
syscall rt_sigaction = 0
syscall rt_sigprocmask = 0
syscall rt_sigaction = 0
syscall rt_sigaction = 0
syscall sigaltstack = 0
syscall brk = 0x7f2f80000000
syscall brk = 0x7f2f80001000
syscall rt_sigprocmask = 0
syscall rt_sigprocmask = 0
syscall getrandom = 16
syscall brk = 0x7f2f80002000
syscall fstat = -77
syscall lseek = -38
syscall read = -9
syscall execve905 = -38
cpuid(0, 0) = (0000001b, 756e6547, 6c65746e, 49656e69)
cpuid(0x7, 0) = (0x2, f2bf27ef, 40405f5e, bc000410)
cpuid(0x1, 0) = (000706e5, 0x4dd500, 7ffafbbf, bfebfbff)
syscall getrandom = 1
syscall getrandom = 32
cpuid(0x1, 0) = (000706e5, 0x4dd500, 7ffafbbf, bfebfbff)
cpuid(0x7, 0) = (0x2, f2bf27ef, 40405f5e, bc000410)
syscall execve905 = -38
syscall getrandom = 32
syscall getrandom = 32
syscall getrandom = 32
syscall getrandom = 32
syscall getrandom = 32
syscall getrandom = 32
syscall brk = 0x7f2f80009000
syscall brk = 0x7f2f8000d000
syscall brk = 0x7f2f8000e000
syscall brk = 0x7f2f8000f000
syscall brk = 0x7f2f80010000
syscall brk = 0x7f2f80011000
syscall brk = 0x7f2f80012000
syscall brk = 0x7f2f80013000
syscall brk = 0x7f2f80014000
syscall brk = 0x7f2f80015000
syscall brk = 0x7f2f80016000
syscall brk = 0x7f2f80017000
syscall brk = 0x7f2f80018000
syscall brk = 0x7f2f80019000
syscall brk = 0x7f2f8001a000
syscall brk = 0x7f2f8001b000
syscall brk = 0x7f2f8001c000
syscall brk = 0x7f2f8001d000
syscall brk = 0x7f2f8001e000
syscall getrandom = 32
syscall brk = 0x7f2f80025000
syscall brk = 0x7f2f80029000
syscall fstat = -77
syscall lseek = -38
syscall read = 32
syscall read = 32
syscall read = 64
syscall read = 128
syscall read = 256
syscall read = 512
syscall read = 0x400
syscall read = 0x800
syscall read = 0x1000
syscall brk = 0x7f2f8002e000
syscall read = 0x2000
syscall brk = 0x7f2f80037000
syscall read = 0x4000
syscall brk = 0x7f2f80048000
syscall read = 0x8000
syscall brk = 0x7f2f80069000
syscall read = 0x4a8b
syscall read = 0
syscall close [src/backend/sgx/thread.rs:298] &_syscall = Payload {
    num: 3,
    argv: [
        3,
        0xffffffffffffffff,
        0xffffffffffffffff,
        0xffffffffffffffff,
        0xffffffffffffffff,
        0xffffffffffffffff,
    ],
    ret: [
        0xffffffffffffffda,
        0,
    ],
}
= 0
cpuid(0, 0) = (0000001b, 756e6547, 6c65746e, 49656e69)
cpuid(0x1, 0) = (000706e5, 0x4dd500, 7ffafbbf, bfebfbff)
cpuid(0x7, 0) = (0x2, f2bf27ef, 40405f5e, bc000410)
cpuid(0x4c4b400, 0) = (0x4c4b408, 0, 0, 0)
cpuid(0x4c4b401, 0) = (0, 0, 0x79, 2c100800)
cpuid(0000000d, 0x1) = (0000000f, 0x3dc, 0x834, 0)
syscall rt_sigaction = 0
syscall rt_sigaction = 0
syscall rt_sigaction = 0
syscall brk = 0x7f2f8006a000
syscall brk = 0x7f2f8006b000
syscall brk = 0x7f2f8006c000
syscall brk = 0x7f2f8006d000
syscall brk = 0x7f2f8006e000
syscall brk = 0x7f2f8006f000
syscall brk = 0x7f2f80070000
syscall brk = 0x7f2f80071000
syscall brk = 0x7f2f80072000
syscall brk = 0x7f2f80073000
syscall brk = 0x7f2f80075000
syscall brk = 0x7f2f80082000
syscall brk = 0x7f2f80083000
syscall brk = 0x7f2f80084000
syscall brk = 0x7f2f80085000
syscall brk = 0x7f2f80086000
syscall brk = 0x7f2f80087000
syscall brk = 0x7f2f80088000
syscall brk = 0x7f2f80089000
syscall brk = 0x7f2f8008a000
syscall brk = 0x7f2f8008b000
syscall brk = 0x7f2f8008c000
syscall brk = 0x7f2f8009a000
syscall brk = 0x7f2f8009b000
syscall brk = 0x7f2f8009d000
syscall brk = 0x7f2f8009f000
syscall brk = 0x7f2f800a2000
syscall brk = 0x7f2f800a8000
syscall brk = 0x7f2f800ab000
syscall brk = 0x7f2f800b1000
syscall brk = 0x7f2f800b7000
syscall brk = 0x7f2f800c3000
syscall brk = 0x7f2f800c4000
syscall brk = 0x7f2f800c5000
syscall brk = 0x7f2f800cb000
syscall brk = 0x7f2f800cd000
syscall brk = 0x7f2f800d0000
syscall brk = 0x7f2f800d3000
syscall brk = 0x7f2f800d9000
syscall brk = 0x7f2f800e5000
syscall brk = 0x7f2f800f0000
syscall brk = 0x7f2f80105000
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall brk = 0x7f2f80110000
syscall brk = 0x7f2f80122000
syscall brk = 0x7f2f8012d000
syscall brk = 0x7f2f80142000
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall brk = 0x7f2f8016b000
syscall madvise = 0
syscall brk = 0x7f2f80174000
syscall brk = 0x7f2f80189000
syscall brk = 0x7f2f8019e000
syscall brk = 0x7f2f801c7000
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall brk = 0x7f2f801ed000
syscall brk = 0x7f2f80202000
syscall brk = 0x7f2f8022b000
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall brk = 0x7f2f80254000
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall brk = 0x7f2f80281000
syscall mmap M 0x007f2ffffa6000 0x00000000059000
= 0x7f2ffffa6000
syscall mremap = -38
syscall mmap M 0x007f2fffef5000 0x000000000b1000
= 0x7f2fffef5000
syscall munmap = 0
syscall mmap M 0x007f2fffea4000 0x00000000051000
= 0x7f2fffea4000
syscall mremap = -38
syscall mmap M 0x007f2fffe03000 0x000000000a1000
= 0x7f2fffe03000
syscall munmap = 0
syscall munmap = 0
syscall brk = 0x7f2f802a0000
syscall brk = 0x7f2f802c1000
syscall brk = 0x7f2f802e2000
syscall brk = 0x7f2f802f7000
syscall brk = 0x7f2f8030c000
syscall brk = 0x7f2f80325000
syscall mmap M 0x007f2fffdb8000 0x0000000004b000
= 0x7f2fffdb8000
syscall brk = 0x7f2f8034e000
syscall mmap M 0x007f2fffd67000 0x00000000051000
= 0x7f2fffd67000
syscall brk = 0x7f2f80380000
syscall munmap = 0
syscall madvise = 0
syscall madvise = 0
syscall mmap M 0x007f2fffd15000 0x00000000052000
= 0x7f2fffd15000
syscall mremap = -38
syscall mmap M 0x007f2fffc72000 0x000000000a3000
= 0x7f2fffc72000
syscall munmap = 0
syscall mmap M 0x007f2fffbd1000 0x000000000a1000
= 0x7f2fffbd1000
syscall munmap = 0
syscall madvise = 0
syscall munmap = 0
syscall madvise = 0
syscall mmap M 0x007f2fffb6c000 0x00000000065000
= 0x7f2fffb6c000
syscall mremap = -38
syscall mmap M 0x007f2fffaa3000 0x000000000c9000
= 0x7f2fffaa3000
syscall munmap = 0
syscall munmap = 0
syscall munmap = 0
syscall munmap = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall mmap M 0x007f2fffa4a000 0x00000000059000
= 0x7f2fffa4a000
syscall mmap M 0x007f2fff9f9000 0x00000000051000
= 0x7f2fff9f9000
syscall munmap = 0
syscall mmap M 0x007f2fff9a8000 0x00000000051000
= 0x7f2fff9a8000
syscall madvise = 0
syscall munmap = 0
syscall munmap = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall mmap M 0x007f2fff912000 0x00000000096000
= 0x7f2fff912000
syscall madvise = 0
syscall madvise = 0
syscall madvise = 0
syscall mprotect = 0
syscall mmap M 0x007f2fff90f000 0x00000000003000
= 0x7f2fff90f000
syscall mprotect = 0
syscall getpid = 0x3e8
syscall mmap M 0x007f2fff90c000 0x00000000003000
= 0x7f2fff90c000
syscall mprotect = 0
syscall getpid = 0x3e8
syscall ioctl = -95
syscall ioctl = -95
syscall ioctl = -95
syscall sigaltstack = 0
syscall mmap M 0x007f2fff8fb000 0x00000000011000
= 0x7f2fff8fb000
syscall mprotect = 0
syscall sigaltstack = 0
thread 'main' panicked at 'Unexpected PF: address: 0x007f2fff910000, error code 0x15', src/backend/sgx/thread.rs:223:21
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'zerooneone' panicked at 'assertion failed: `(left == right)`
  left: `[]`,
 right: `[84, 98, 98, 113, 32, 122, 98, 101, 97, 118, 97, 116, 44, 32, 103, 117, 110, 103, 39, 102, 32, 110, 32, 97, 118, 112, 114, 32, 103, 97, 114, 103, 114, 97, 97, 111, 110, 46, 10, 48, 49, 49, 56, 32, 57, 57, 57, 32, 56, 56, 49, 32, 57, 57, 57, 32, 49, 49, 57, 32, 55, 50, 53, 32, 51, 10]`: Expected contents of stdout output differs', tests/common/mod.rs:108:13
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test zerooneone ... FAILED

failures:

failures:
    zerooneone

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 8 filtered out; finished in 22.38s

error: test failed, to rerun pass '--test wasmldr_tests'
```

**Comment by jarkkojs** [comment]
@haraldh What do you think?

**Comment by haraldh** [comment]
I think @bstrie should also generate a `syscall_no.to_string()` function for our libc, which we call when `feature = "dbg"`.

**Comment by jarkkojs** [comment]
IMHO, there should be at least a feature to suppress also `clock_gettime`. I.e. optimal would be:

```
   Compiling enarx v0.3.0 (/home/jarkko/Projects/enarx)
    Finished test [unoptimized + debuginfo] target(s) in 10.70s
     Running tests/wasmldr_tests.rs (target/debug/deps/wasmldr_tests-ebd88a576bc4239c)

running 1 test
syscall mmap M 0x007f517ffff000-0x007f517ffff548
= 0x7f517ffff000
syscall arch_prctl = 0
syscall set_tid_address = 1
syscall poll [src/backend/sgx/thread.rs:298] &_syscall = Payload {
    num: 7,
    argv: [
        0,
        3,
        0,
        0xffffffffffffffff,
        0xffffffffffffffff,
        0xffffffffffffffff,
    ],
    ret: [
        0xffffffffffffffda,
        0,
    ],
}
= 1
syscall rt_sigaction = 0
syscall rt_sigaction = 0
syscall rt_sigprocmask = 0
syscall rt_sigaction = 0
syscall rt_sigaction = 0
syscall sigaltstack = 0
syscall brk = 0x7f5108000000
syscall brk = 0x7f5108001000
syscall rt_sigprocmask = 0
syscall rt_sigprocmask = 0
syscall getrandom = 16
syscall brk = 0x7f5108002000
syscall fstat = -77
syscall lseek = -38
syscall read = -9
syscall execve905 = -38
cpuid(0, 0) = (0000001b, 756e6547, 6c65746e, 49656e69)
cpuid(0x7, 0) = (0x2, f2bf27ef, 40405f5e, bc000410)
cpuid(0x1, 0) = (000706e5, 0x189c0, 7ffafbbf, bfebfbff)
syscall getrandom = 1
syscall getrandom = 32
cpuid(0x1, 0) = (000706e5, 0x189c0, 7ffafbbf, bfebfbff)
cpuid(0x7, 0) = (0x2, f2bf27ef, 40405f5e, bc000410)
syscall execve905 = -38
syscall getrandom = 32
syscall getrandom = 32
syscall getrandom = 32
syscall getrandom = 32
syscall getrandom = 32
syscall getrandom = 32
syscall brk = 0x7f5108009000
syscall brk = 0x7f510800d000
syscall brk = 0x7f510800e000
syscall brk = 0x7f510800f000
syscall brk = 0x7f5108010000
syscall brk = 0x7f5108011000
syscall brk = 0x7f5108012000
syscall brk = 0x7f5108013000
syscall brk = 0x7f5108014000
syscall brk = 0x7f5108015000
syscall brk = 0x7f5108016000
syscall brk = 0x7f5108017000
syscall brk = 0x7f5108018000
syscall brk = 0x7f5108019000
syscall brk = 0x7f510801a000
syscall brk = 0x7f510801b000
syscall brk = 0x7f510801c000
syscall brk = 0x7f510801d000
syscall brk = 0x7f510801e000
syscall getrandom = 32
syscall brk = 0x7f5108025000
syscall brk = 0x7f5108029000
syscall fstat = -77
syscall lseek = -38
syscall read = 32
syscall read = 32
syscall read = 64
syscall read = 126
syscall read = 0
syscall close [src/backend/sgx/thread.rs:298] &_syscall = Payload {
    num: 3,
    argv: [
        3,
        0xffffffffffffffff,
        0xffffffffffffffff,
        0xffffffffffffffff,
        0xffffffffffffffff,
        0xffffffffffffffff,
    ],
    ret: [
        0xffffffffffffffda,
        0,
    ],
}
= 0
cpuid(0, 0) = (0000001b, 756e6547, 6c65746e, 49656e69)
cpuid(0x1, 0) = (000706e5, 0x189c0, 7ffafbbf, bfebfbff)
cpuid(0x7, 0) = (0x2, f2bf27ef, 40405f5e, bc000410)
cpuid(0x4c4b400, 0) = (0x4c4b408, 0, 0, 0)
cpuid(0x4c4b401, 0) = (0, 0, 0x79, 2c100800)
cpuid(0000000d, 0x1) = (0000000f, 0x3dc, 0x834, 0)
syscall rt_sigaction = 0
syscall rt_sigaction = 0
syscall rt_sigaction = 0
syscall brk = 0x7f510802a000
syscall brk = 0x7f510802b000
syscall brk = 0x7f510802c000
syscall brk = 0x7f510802d000
syscall brk = 0x7f510802e000
syscall brk = 0x7f510802f000
syscall brk = 0x7f5108030000
syscall brk = 0x7f5108031000
syscall brk = 0x7f5108032000
syscall brk = 0x7f5108033000
syscall brk = 0x7f5108034000
syscall brk = 0x7f5108035000
syscall brk = 0x7f5108036000
syscall brk = 0x7f5108037000
syscall brk = 0x7f5108038000
syscall brk = 0x7f5108039000
syscall brk = 0x7f510803a000
syscall brk = 0x7f510803b000
syscall brk = 0x7f510803c000
syscall brk = 0x7f510803d000
syscall brk = 0x7f510803e000
syscall brk = 0x7f510803f000
syscall brk = 0x7f5108040000
syscall brk = 0x7f5108041000
syscall brk = 0x7f5108043000
syscall brk = 0x7f5108044000
syscall brk = 0x7f5108045000
syscall brk = 0x7f5108046000
syscall brk = 0x7f5108047000
syscall brk = 0x7f5108048000
syscall brk = 0x7f5108049000
syscall brk = 0x7f510804a000
syscall brk = 0x7f510804b000
syscall brk = 0x7f510804c000
syscall brk = 0x7f510804d000
syscall brk = 0x7f510804e000
syscall brk = 0x7f510804f000
syscall brk = 0x7f5108050000
syscall brk = 0x7f5108051000
syscall brk = 0x7f5108052000
syscall brk = 0x7f5108053000
syscall brk = 0x7f5108054000
syscall brk = 0x7f5108055000
syscall brk = 0x7f5108056000
syscall brk = 0x7f5108057000
syscall brk = 0x7f5108058000
syscall brk = 0x7f510805a000
syscall brk = 0x7f510805d000
syscall brk = 0x7f510805e000
syscall brk = 0x7f510805f000
syscall brk = 0x7f5108061000
syscall brk = 0x7f5108062000
syscall brk = 0x7f5108063000
syscall brk = 0x7f5108065000
syscall brk = 0x7f5108068000
syscall brk = 0x7f5108079000
syscall mmap M 0x007f517ffeb000-0x007f517ffff000
= 0x7f517ffeb000
syscall mprotect = 0
syscall mmap M 0x007f517ffe8000-0x007f517ffeb000
= 0x7f517ffe8000
syscall mprotect = 0
syscall getpid = 0x3e8
syscall ioctl = -95
syscall ioctl = -95
syscall ioctl = -95
syscall sigaltstack = 0
syscall mmap M 0x007f517ffd7000-0x007f517ffe8000
= 0x7f517ffd7000
syscall mprotect = 0
syscall sigaltstack = 0
thread 'main' panicked at 'Unexpected PF: address: 0x007f517ffe9000, error code 0x15', src/backend/sgx/thread.rs:223:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'hello_wasi_snapshot1' panicked at 'assertion failed: `(left == right)`
  left: `[]`,
 right: `[72, 101, 108, 108, 111, 44, 32, 119, 111, 114, 108, 100, 33, 10]`: Expected contents of stdout output differs', tests/common/mod.rs:108:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test hello_wasi_snapshot1 ... FAILED

failures:

failures:
    hello_wasi_snapshot1

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 8 filtered out; finished in 1.70s

error: test failed, to rerun pass '--test wasmldr_tests'
```
