### ISSUE TITLE
[Bug]: integration tests fail, if RUST_BACKTRACE is set

### ISSUE THREAD

**Issue by haraldh** [enarx/enarx#2312]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Current Behaviour

```
❯ unset RUST_BACKTRACE; cargo test --test integration client
    Finished test [unoptimized + debuginfo] target(s) in 0.20s
     Running tests/integration.rs (target/debug/deps/integration-f9aac8553e5b211e)

running 2 tests
test client::test_config_init ... ok
test client::full ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 43 filtered out; finished in 0.91s
```

````
❯ RUST_BACKTRACE=1 cargo test --test integration client
    Finished test [unoptimized + debuginfo] target(s) in 0.20s
     Running tests/integration.rs (target/debug/deps/integration-f9aac8553e5b211e)

running 2 tests
test client::test_config_init ... FAILED
test client::full ... FAILED

failures:

---- client::test_config_init stdout ----
thread 'client::test_config_init' panicked at 'expected output differs from received output:

```command
enarx config init
```

```expected
Error: "Enarx.toml" does already exist.
```

```received
Error: "Enarx.toml" does already exist.

Stack backtrace:
   0: anyhow::error::<impl anyhow::Error>::msg
             at /home/harald/.cargo/registry/src/index.crates.io-93a9e06d8945f2c0/anyhow-1.0.65/src/error.rs:83:36
   1: anyhow::__private::format_err
             at /home/harald/.cargo/registry/src/index.crates.io-93a9e06d8945f2c0/anyhow-1.0.65/src/lib.rs:669:13
   2: enarx::cli::config::init::Options::execute
             at /home/harald/git/enarx/enarx/src/cli/config/init.rs:19:13
   3: enarx::cli::config::Subcommands::dispatch
             at /home/harald/git/enarx/enarx/src/cli/config/mod.rs:16:32
   4: enarx::cli::Subcommands::dispatch
             at /home/harald/git/enarx/enarx/src/cli/mod.rs:90:37
   5: enarx::cli::Options::execute
             at /home/harald/git/enarx/enarx/src/cli/mod.rs:55:9
   6: enarx::main
             at /home/harald/git/enarx/enarx/src/main.rs:21:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/core/src/ops/function.rs:251:5
   8: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/std/src/sys_common/backtrace.rs:121:18
   9: std::rt::lang_start::{{closure}}
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/std/src/rt.rs:166:18
  10: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/core/src/ops/function.rs:286:13
  11: std::panicking::try::do_call
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/std/src/panicking.rs:483:40
  12: std::panicking::try
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/std/src/panicking.rs:447:19
  13: std::panic::catch_unwind
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/std/src/panic.rs:137:14
  14: std::rt::lang_start_internal::{{closure}}
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/std/src/rt.rs:148:48
  15: std::panicking::try::do_call
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/std/src/panicking.rs:483:40
  16: std::panicking::try
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/std/src/panicking.rs:447:19
  17: std::panic::catch_unwind
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/std/src/panic.rs:137:14
  18: std::rt::lang_start_internal
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/std/src/rt.rs:148:20
  19: std::rt::lang_start
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/std/src/rt.rs:165:17
  20: main
  21: __libc_start_call_main
  22: __libc_start_main@GLIBC_2.2.5
  23: _start
```
', tests/client/mod.rs:213:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/core/src/panicking.rs:65:14
   2: integration::client::util::enarx
             at /home/harald/git/enarx/enarx/tests/client/util.rs:81:9
   3: integration::client::test_config_init
             at /home/harald/git/enarx/enarx/tests/client/mod.rs:213:5
   4: integration::client::test_config_init::{{closure}}
             at /home/harald/git/enarx/enarx/tests/client/mod.rs:209:1
   5: core::ops::function::FnOnce::call_once
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/core/src/ops/function.rs:251:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/core/src/ops/function.rs:251:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- client::full stdout ----
thread 'client::full' panicked at 'expected output differs from received output:

```command
enarx user info localhost:41339/testuser
```

```expected
Error: Failed to get record for user: testuser

Caused by:
    0: GET request failed
    1: request failed with status code `401`
    2: User with OpenID Connect subject `test|subject` not found
```

```received
Error: Failed to get record for user: testuser

Caused by:
    0: GET request failed
    1: request failed with status code `401`
    2: User with OpenID Connect subject `test|subject` not found

Stack backtrace:
   0: anyhow::kind::Adhoc::new
             at /home/harald/.cargo/registry/src/index.crates.io-93a9e06d8945f2c0/anyhow-1.0.65/src/kind.rs:70:36
   1: drawbridge_client::entity::parse_ureq_error
             at /home/harald/.cargo/registry/src/index.crates.io-93a9e06d8945f2c0/drawbridge-client-0.2.3/src/entity.rs:42:17
   2: core::ops::function::FnOnce::call_once
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/core/src/ops/function.rs:251:5
   3: core::result::Result<T,E>::map_err
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/core/src/result.rs:861:27
   4: drawbridge_client::entity::Entity<C,E>::get
             at /home/harald/.cargo/registry/src/index.crates.io-93a9e06d8945f2c0/drawbridge-client-0.2.3/src/entity.rs:145:19
   5: drawbridge_client::entity::Entity<C,E>::get_json
             at /home/harald/.cargo/registry/src/index.crates.io-93a9e06d8945f2c0/drawbridge-client-0.2.3/src/entity.rs:186:27
   6: drawbridge_client::user::User<S>::get
             at /home/harald/.cargo/registry/src/index.crates.io-93a9e06d8945f2c0/drawbridge-client-0.2.3/src/user.rs:35:9
   7: enarx::cli::user::info::Options::execute
             at /home/harald/git/enarx/enarx/src/cli/user/info.rs:36:22
   8: enarx::cli::user::Subcommands::dispatch
             at /home/harald/git/enarx/enarx/src/cli/user/mod.rs:24:32
   9: enarx::cli::Subcommands::dispatch
             at /home/harald/git/enarx/enarx/src/cli/mod.rs:100:35
  10: enarx::cli::Options::execute
             at /home/harald/git/enarx/enarx/src/cli/mod.rs:55:9
  11: enarx::main
             at /home/harald/git/enarx/enarx/src/main.rs:21:5
  12: core::ops::function::FnOnce::call_once
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/core/src/ops/function.rs:251:5
  13: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/std/src/sys_common/backtrace.rs:121:18
  14: std::rt::lang_start::{{closure}}
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/std/src/rt.rs:166:18
  15: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/core/src/ops/function.rs:286:13
  16: std::panicking::try::do_call
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/std/src/panicking.rs:483:40
  17: std::panicking::try
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/std/src/panicking.rs:447:19
  18: std::panic::catch_unwind
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/std/src/panic.rs:137:14
  19: std::rt::lang_start_internal::{{closure}}
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/std/src/rt.rs:148:48
  20: std::panicking::try::do_call
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/std/src/panicking.rs:483:40
  21: std::panicking::try
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/std/src/panicking.rs:447:19
  22: std::panic::catch_unwind
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/std/src/panic.rs:137:14
  23: std::rt::lang_start_internal
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/std/src/rt.rs:148:20
  24: std::rt::lang_start
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/std/src/rt.rs:165:17
  25: main
  26: __libc_start_call_main
  27: __libc_start_main@GLIBC_2.2.5
  28: _start
```
', tests/client/mod.rs:29:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/core/src/panicking.rs:65:14
   2: integration::client::util::enarx
             at /home/harald/git/enarx/enarx/tests/client/util.rs:81:9
   3: integration::client::cli_test
             at /home/harald/git/enarx/enarx/tests/client/mod.rs:29:5
   4: integration::client::full::{{closure}}
             at /home/harald/git/enarx/enarx/tests/client/mod.rs:200:5
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/core/src/future/mod.rs:91:19
   6: <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll::{{closure}}
             at /home/harald/.cargo/registry/src/index.crates.io-93a9e06d8945f2c0/async-std-1.12.0/src/task/builder.rs:199:17
   7: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::{{closure}}
             at /home/harald/.cargo/registry/src/index.crates.io-93a9e06d8945f2c0/async-std-1.12.0/src/task/task_locals_wrapper.rs:60:13
   8: std::thread::local::LocalKey<T>::try_with
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/std/src/thread/local.rs:446:16
   9: std::thread::local::LocalKey<T>::with
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/std/src/thread/local.rs:422:9
  10: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current
             at /home/harald/.cargo/registry/src/index.crates.io-93a9e06d8945f2c0/async-std-1.12.0/src/task/task_locals_wrapper.rs:55:9
  11: <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll
             at /home/harald/.cargo/registry/src/index.crates.io-93a9e06d8945f2c0/async-std-1.12.0/src/task/builder.rs:197:13
  12: <futures_lite::future::Or<F1,F2> as core::future::future::Future>::poll
             at /home/harald/.cargo/registry/src/index.crates.io-93a9e06d8945f2c0/futures-lite-1.12.0/src/future.rs:526:33
  13: async_executor::Executor::run::{{closure}}
             at /home/harald/.cargo/registry/src/index.crates.io-93a9e06d8945f2c0/async-executor-1.4.1/src/lib.rs:242:31
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/core/src/future/mod.rs:91:19
  15: async_executor::LocalExecutor::run::{{closure}}
             at /home/harald/.cargo/registry/src/index.crates.io-93a9e06d8945f2c0/async-executor-1.4.1/src/lib.rs:447:33
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/core/src/future/mod.rs:91:19
  17: async_io::driver::block_on
             at /home/harald/.cargo/registry/src/index.crates.io-93a9e06d8945f2c0/async-io-1.9.0/src/driver.rs:142:33
  18: async_global_executor::reactor::block_on::{{closure}}
             at /home/harald/.cargo/registry/src/index.crates.io-93a9e06d8945f2c0/async-global-executor-2.3.0/src/reactor.rs:3:18
  19: async_global_executor::reactor::block_on
             at /home/harald/.cargo/registry/src/index.crates.io-93a9e06d8945f2c0/async-global-executor-2.3.0/src/reactor.rs:12:5
  20: async_global_executor::executor::block_on::{{closure}}
             at /home/harald/.cargo/registry/src/index.crates.io-93a9e06d8945f2c0/async-global-executor-2.3.0/src/executor.rs:26:36
  21: std::thread::local::LocalKey<T>::try_with
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/std/src/thread/local.rs:446:16
  22: std::thread::local::LocalKey<T>::with
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/std/src/thread/local.rs:422:9
  23: async_global_executor::executor::block_on
             at /home/harald/.cargo/registry/src/index.crates.io-93a9e06d8945f2c0/async-global-executor-2.3.0/src/executor.rs:26:5
  24: async_std::task::builder::Builder::blocking::{{closure}}::{{closure}}
             at /home/harald/.cargo/registry/src/index.crates.io-93a9e06d8945f2c0/async-std-1.12.0/src/task/builder.rs:171:25
  25: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::{{closure}}
             at /home/harald/.cargo/registry/src/index.crates.io-93a9e06d8945f2c0/async-std-1.12.0/src/task/task_locals_wrapper.rs:60:13
  26: std::thread::local::LocalKey<T>::try_with
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/std/src/thread/local.rs:446:16
  27: std::thread::local::LocalKey<T>::with
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/std/src/thread/local.rs:422:9
  28: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current
             at /home/harald/.cargo/registry/src/index.crates.io-93a9e06d8945f2c0/async-std-1.12.0/src/task/task_locals_wrapper.rs:55:9
  29: async_std::task::builder::Builder::blocking::{{closure}}
             at /home/harald/.cargo/registry/src/index.crates.io-93a9e06d8945f2c0/async-std-1.12.0/src/task/builder.rs:168:17
  30: std::thread::local::LocalKey<T>::try_with
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/std/src/thread/local.rs:446:16
  31: std::thread::local::LocalKey<T>::with
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/std/src/thread/local.rs:422:9
  32: async_std::task::builder::Builder::blocking
             at /home/harald/.cargo/registry/src/index.crates.io-93a9e06d8945f2c0/async-std-1.12.0/src/task/builder.rs:161:9
  33: async_std::task::block_on::block_on
             at /home/harald/.cargo/registry/src/index.crates.io-93a9e06d8945f2c0/async-std-1.12.0/src/task/block_on.rs:33:5
  34: integration::client::full
             at /home/harald/git/enarx/enarx/tests/client/mod.rs:193:1
  35: integration::client::full::{{closure}}
             at /home/harald/git/enarx/enarx/tests/client/mod.rs:193:1
  36: core::ops::function::FnOnce::call_once
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/core/src/ops/function.rs:251:5
  37: core::ops::function::FnOnce::call_once
             at /rustc/215e3cd218b83b8a3152d84d92f17109253c25e1/library/core/src/ops/function.rs:251:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    client::full
    client::test_config_init

test result: FAILED. 0 passed; 2 failed; 0 ignored; 0 measured; 43 filtered out; finished in 0.13s

error: test failed, to rerun pass `--test integration`
````

### Expected Behaviour

Tests succeeding regardless of `RUST_BACKTRACE` environment setting.

### Environment Information

```
❯ git show -s
commit 56809f296055fbcb04514c62e5824ba0fb1d8069 (HEAD -> main, origin/main, origin/HEAD)
```

**Comment by dpal** [comment]
Ben will unset the ENV VAR for this specific test. Will look today.
